### PR TITLE
Register `net.postgis.jdbc.DriverWrapper` via `java.sql.Driver` service

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by soc** [comment]
Should address https://github.com/postgis/postgis-java/issues/90, @OrangeDog, can you confirm?

**Comment by soc** [comment]
@OrangeDog Just wondering, wouldn't we need to also add an entry for `DriverWrapperLW`?

**Comment by OrangeDog** [comment]
`DriverManager.getDriver("jdbc:postgresql_postGIS:/")` would probably be the test.

**Comment by phillipross** [comment]
An automated test would be best.  Thanks!

**Comment by soc** [comment]
@OrangeDog Ping?

**Comment by OrangeDog** [comment]
Hello? What are you expecting me to do?

**Comment by soc** [comment]
> @OrangeDog Just wondering, wouldn't we need to also add an entry for DriverWrapperLW?

**Comment by OrangeDog** [comment]
I have no idea.

**Comment by soc** [comment]
Ok, thanks!

**Comment by soc** [comment]
@phillipross I registered all three drivers and added a test to verify that loading them works. Does this look good to you?

**Comment by phillipross** [comment]
> @phillipross I registered all three drivers and added a test to verify that loading them works. Does this look good to you?

Yes, this looks good to me.  Could I ask you to add  a bit of javadoc to the test class to explain what it's testing? Thanks!

**Comment by soc** [comment]
Done!

**Comment by phillipross** [comment]
Thanks @soc for the code contribution and thanks @OrangeDog for filing the issue!

**Pull request merged**
