### PR TITLE
Rename package, fix Java module issues, etc.

### PR DESCRIPTION
**Pull request by soc**
Just a rough sketch, not meant to be merged into master.

I tried to keep every refactoring in a separate commit – in the end it perhaps makes sense to squash some or all commits.

### CODE REVIEW

**Comment by phillipross** [comment]
I'd recommend not spending too much time worrying about the organization of changes into commits, as long as you're mostly aiming to keep the changes as "atomic" as possible.  You can always rebase-and-force-push the changes to reorganize what changes go into what commits on the PR branch.  Depending on how atomic the final commits are, we can determine if a merge commit or squash commit makes more sense.

Looks like the CI choked on some tests at some point, but so far I'm liking the direction of what I see you doing.

My first though:  does it make sense to target Java11 rather than Java9?  The disadvantage of supporting intermediate non-LTS versions is that it would be setting a precedent of allowing people to opt for binding themselves to non-LTS behaviors by these intermediate versions.  The risk is probably low, but I usually try not nudge people toward LTS releases when/where possible.  In general it's fine for non-LTS releases that are later than the lastest LTS release, but the intermediate non-LTS releases are already not considered supported.  It may not even matter, but it's something to think about and consider.

My second thought:  making changes to the osgeo smoke test util should probably be communicated to osgeo packaging folks who might have dependencies baked into their own distribution pipelines.  A courteous heads before releasing a new version with these changes might be in order.

And as always... thanks for helping with this!

**Comment by soc** [comment]
Hey @phillipross!

>  Depending on how atomic the final commits are, we can determine if a merge commit or squash commit makes more sense.

Sounds good!

>  does it make sense to target Java11 rather than Java9?

I picked Java 9, because it was the first version with modules – and because it helped me with sorting out the split packages.

Now that the issues have been resolved, we could also go back to an older version (e. g. Java 8), and add `Automatic-Module-Name`s to the MANIFEST.MF files instead of using module-info.java files – then we wouldn't have any version requirement at all.

> making changes to the osgeo smoke test util should probably be communicated to osgeo packaging folks

Agreed, I didn't know about that.

The motivation of turning the osgeo module into a general smoketest module was because the `example` packages in the "real" modules couldn't stay there, because they were a) clashing b) would have been needed to be exported in module-info.java to be actually useful.

**Comment by phillipross** [comment]
I would say that it's not necessary to provide backwards compatibility to Java8 in this next release.  It's not spelled out in any documentation unfortunately, but I believe the only changes between 2.4.x and 2.5.x were the decoupling of the jdbc and geometry classes into separate artifacts.  This was done to allow other jdbc drivers to use the geometry classes without conflicting with the postgresql jdbc driver.  This was also the release where the incompatibility with JPMS was created since the classes were factored out into separate artifacts but were not placed in separate packages.  Consequently the artifacts use the same packages which was the problem for JPMS projects.  Going forward, JPMS projects should target newer releases and won't have to worry about Java8.  I may be missing something in my reasoning, and admittedly I've not considered projects using multi-release jars and whatnot, but that's what I've been thinking so far.

I think it's fair to say 2.x releases are to be used by Java8 users until they can update to Java11 and future releases can/will drop support for Java8.  While maintaining backward compat with Java8 might be possible for future releases, maintenance cost exceeds the current community's ability to maintain postgis-java 😞 Really I don't think it's too unfair since there aren't any new features that are being written into these new releases.  It will only matter when we begin doing future releases with new features which is a whole other roadmap.

I really don't know if osgeo is still relying on the smoke test so it may be able to be dropped completely if nobody actually depends on it anymore.  But I just wanted to give a heads up.  Giving them an alternate way to smoke test a postgis installation with the java driver may be all that is required by them.  A CLI interface to invoke the test(s) might have been their only requirement.

The notes about autoregistration with the postgresql jdbc driver are VERY dated, and we can break backwards compatibility for future releases in this case and only use and support the current modern registration process.  Is there an issue with keeping the driverconfig.properties file in the org.postgresql package within the artifact or something?  My vision had been for future releases to drop compatibility and throw away the driver wrapper method to handle programatic registration of the classes with the jdbc driver and only use the driverconfig.properties registration mechanism since that's what all supported postgres jdbc driver versions support these days.

**Comment by soc** [comment]
> I've not considered projects using multi-release jars and whatnot, but that's what I've been thinking so far.

I wouldn't bother with it, to be honest.

> I really don't know if osgeo is still relying on the smoke test so it may be able to be dropped completely if nobody actually depends on it anymore.

It's still there, it just has been renamed, when the package names have been adjusted. It's the `OSGeo` one in the `smoketest` module.

> Is there an issue with keeping the driverconfig.properties file in the org.postgresql package within the artifact or something?

Yes, it's not allowed when using module-info.java files (it is with Automatic-Module-Name though).

**Comment by phillipross** [comment]
@soc just checking in... are you blocked on something with this PR or just not had the bandwidth to address it?
CI is showing test failures and I wasn't sure if you were trying to figure out the cause of the failures or what.
I've unfortunately had a lack of bandwidth to look closely myself, but if there's anything I or some other contributor could help with please just add it the conversation here.  Thanks!

**Comment by soc** [comment]
Seems related to driver registration:

```
[ERROR]   BoxesTest.testBoxes:64->test:95 Geometries after SQL are not equal expected [BOX3D(1 2 3,4 5 6)] but found [BOX3D(1 2 3,4 5 6)]

[ERROR]   DatatypesAutoRegistrationTest.testAutoRegistration:116 expected [true] but found [false]

[ERROR]   GeographyDatatypeTest.testDatatypes:235 expected [class net.postgis.jdbc.PGgeometry] but found [class org.postgresql.util.PGobject]

[ERROR]   ParserTest.testParser:252->test:310->viaSQL:402 ClassCast class org.postgresql...
```

I guess my approach would be to roll back the module-info.java, add automatic-module-infos to the manifests instead, and then let the postgres people sort out how driver registration is supposed to work with Java modules.

**Comment by phillipross** [comment]
That makes sense... I was actually wondering to myself how the driver registration would need to change in the jpms world.  It seems we'll have to ping postgresql jdbc folks and see if they have plans or ideas for plans of how registration should work.

**Comment by soc** [comment]
@phillipross I pushed a new commit with the changes I mentioned – let's see whether this compiles fine ...

**Comment by soc** [comment]
Build is green – I guess now you need to pick a branch (or move further dev on 2.x to a branch) and merge it, and make a decision on the versioning scheme.

**Comment by phillipross** [comment]
@soc nice work, thanks!

Question: Is it still necessary to have the top-level pom.xml file set the min java property to 9 or can it be reverted back to 1.8?  I ask because it seems that we run into problems with the maven javadoc plugin if we have the min java set to 9 (or 11).  You can probably see this for yourself if you try to build with Java11 and enable the release-sign-artifacts maven profile.  At the moment, the CI doesn't try to build with this profile enabled even though it should probably be changed to do so.

**Comment by soc** [comment]
@phillipross 

> Is it still necessary to have the top-level pom.xml file set the min java property to 9 or can it be reverted back to 1.8?

Should be fine at 8!

**Comment by phillipross** [comment]
@soc I pushed a commit to revert back to Java8.  If you can give this PR one last look to make sure there's nothing missing, I'll merge into master and then rework the versioning/branching separately.  Thanks again!

**Comment by soc** [comment]
@phillipross Looks good to me! Feel free to squash my commits the way you prefer them!

**Comment by soc** [comment]
Hey @phillipross, do you have any plans on a release that includes these changes?

**Comment by phillipross** [comment]
@soc I didn't have any specific plans for a release.  If there's a need for these changes in an official release, I don't see a reason why we couldn't cut a release with these changes.

**Comment by soc** [comment]
Yes, we are still stuck on 2.4, because 2.5 is not module-system compatible. So having the version that fixes released would be good!

**Comment by phillipross** [comment]
Yep, understood.  I'll look into cutting a release this.

**Comment by soc** [comment]
Cool, thanks!

**Comment by phillipross** [comment]
@soc I've just released v2021.1.0 via sonatype.  It should be available in maven central soon.  Apologies for the delay and thanks again for the contributions.

**Comment by soc** [comment]
No worries, thank you, @phillipross!

**Pull request merged**
