### PR TITLE
Treat unsupported URLs as specified in Driver#connect to avoid overwriting the "real" exception

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by phillipross** [comment]
I rebased the branch onto an updated main that has working CI again, but there are still things that fail with the unit tests.  I'm not sure what the best way around these failures are.

**Comment by soc** [comment]
@phillipross You mean it's failing with this PR, or it already fails on master?

**Comment by phillipross** [comment]
It fails with this PR

**Comment by soc** [comment]
Thanks!

**Pull request merged**
