### PR TITLE
Treat unsupported URLs as specified in Driver#connect to avoid overwriting the "real" exception

### PR DESCRIPTION
**Pull request by soc**

### CODE REVIEW

**Comment by phillipross** [comment]
thanks, and i'll fix the CI

**Comment by soc** [comment]
Note that I added an optional second commit, dropping some bits of documentation that I found very confusing, because the mangling of the URL is an implementation detail and not visible to the user.

At least to me it felt as if the documentation indicated something like a reference/out parameter, but Java is purely pass-by-value. Feel free to not merge that one, if I misunderstood something!

**Comment by soc** [comment]
@phillipross Thanks!

**Comment by soc** [comment]
@phillipross Hold on, I just found an issue with the change. I'll fix it!

**Comment by soc** [comment]
Welp, I can't reopen it. :-(

**Comment by soc** [comment]
https://github.com/postgis/postgis-java/pull/115

**Pull request closed without merging**
